//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AXC_EOA_WMSIntegration.Src.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Queries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Queries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AXC_EOA_WMSIntegration.Src.Resource.Queries", typeof(Queries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT CONVERT(NVARCHAR(25),GETDATE(),120).
        /// </summary>
        internal static string axcOFTLG_GET_SERVER_TIME {
            get {
                return ResourceManager.GetString("axcOFTLG_GET_SERVER_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM OITM T0 WHERE T0.ItemCode = &apos;{0}&apos;.
        /// </summary>
        internal static string axcOSYNC_GET_DETAIL_ITEM {
            get {
                return ResourceManager.GetString("axcOSYNC_GET_DETAIL_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --axcOSYNC_GET_LIST_CUSTOMERS
        ///DECLARE @FrCode NVARCHAR(50) = &apos;{0}&apos;
        ///DECLARE @ToCode NVARCHAR(50) = &apos;{1}&apos;
        ///DECLARE @CardType NVARCHAR(1) = &apos;C&apos;
        ///
        ///SELECT &apos;N&apos; &quot;Export&quot;, &apos;N&apos; &quot;Success&quot;, T0.&quot;CardCode&quot;, T0.&quot;CardName&quot;, T0.&quot;CardFName&quot; &quot;Foreign Name&quot;, T1.&quot;GroupName&quot; &quot;Group&quot;, T0.&quot;CntctPrsn&quot; &quot;Contact Person&quot;, T0.&quot;Currency&quot;
        ///	, CASE WHEN T0.&quot;validFor&quot; = &apos;Y&apos; THEN &apos;Y&apos; WHEN ISNULL(T0.&quot;validFor&quot;,&apos;N&apos;) = &apos;N&apos; AND ISNULL(T0.&quot;frozenFor&quot;,&apos;N&apos;) = &apos;N&apos; THEN &apos;Y&apos; ELSE &apos;N&apos; END &quot;Active&quot;
        ///	, T0.&quot;CardCode&quot; &quot;Key&quot;, T0.&quot;CardName&quot; &quot;Name&quot;, T0. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string axcOSYNC_GET_LIST_CUSTOMERS {
            get {
                return ResourceManager.GetString("axcOSYNC_GET_LIST_CUSTOMERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --axcOSYNC_GET_LIST_OBCD	
        ///DECLARE @FrCode NVARCHAR(254) = &apos;{0}&apos;
        ///DECLARE @ToCode NVARCHAR(254) = &apos;{1}&apos;
        ///SELECT &apos;N&apos; &quot;Export&quot;, &apos;N&apos; &quot;Success&quot;, T0.&quot;ItemCode&quot;, T0.&quot;BcdCode&quot;, T1.&quot;UomCode&quot;, T0.&quot;BcdEntry&quot; &quot;Key&quot;, T0.&quot;ItemCode&quot; + &apos; - &apos; + T0.&quot;BcdCode&quot; &quot;Name&quot; , &apos;1470000062&apos; &quot;ObjType&quot; 
        ///	, CAST(&apos;&apos; AS NVARCHAR(254)) &quot;Export Process Remark&quot;
        ///FROM OBCD T0 JOIN OUOM T1 ON T0.&quot;UomEntry&quot; = T1.&quot;UomEntry&quot; 
        ///WHERE T0.&quot;BcdCode&quot; BETWEEN @FrCode AND @ToCode
        ///	OR (
        ///		@FrCode = &apos;&apos; AND @ToCode = &apos;&apos;
        ///	).
        /// </summary>
        internal static string axcOSYNC_GET_LIST_OBCD {
            get {
                return ResourceManager.GetString("axcOSYNC_GET_LIST_OBCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --axcOSYNC_GET_LIST_OBIN
        ///DECLARE @FrCode NVARCHAR(50) = &apos;{0}&apos;
        ///DECLARE @ToCode NVARCHAR(50) = &apos;{1}&apos;
        ///
        ///SELECT &apos;N&apos; &quot;Export&quot;, &apos;N&apos; &quot;Success&quot;, &quot;BinCode&quot;, &quot;WhsCode&quot;, &quot;Disabled&quot;, &quot;ReceiveBin&quot;, &quot;AbsEntry&quot; &quot;Key&quot;, &quot;BinCode&quot; &quot;Name&quot;, &apos;10000206&apos; &quot;ObjType&quot;
        ///	, CAST(&apos;&apos; AS NVARCHAR(254)) &quot;Export Process Remark&quot;
        ///FROM OBIN T0
        ///WHERE T0.&quot;BinCode&quot; BETWEEN @FrCode AND @ToCode
        ///	OR (@FrCode=&apos;&apos; AND @ToCode = &apos;&apos;)
        ///ORDER BY T0.&quot;BinCode&quot;.
        /// </summary>
        internal static string axcOSYNC_GET_LIST_OBIN {
            get {
                return ResourceManager.GetString("axcOSYNC_GET_LIST_OBIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT &apos;2V&apos; &quot;Code&quot;, &apos;VENDOR&apos; &quot;Name&quot; 
        /// UNION ALL SELECT &apos;2C&apos;, &apos;CUSTOMER&apos;
        /// UNION ALL SELECT &apos;4&apos;, &apos;ITEM&apos;
        /// UNION ALL SELECT &apos;52&apos;, &apos;ITEM_CATEGORY&apos;
        /// UNION ALL SELECT &apos;43&apos;, &apos;BRAND&apos;
        /// UNION ALL SELECT &apos;1470000062&apos;, &apos;BAR_CODE&apos;
        /// UNION ALL SELECT &apos;64&apos;, &apos;WAREHOUSE&apos;
        /// UNION ALL SELECT &apos;10000206&apos;, &apos;BIN&apos;
        /// UNION ALL SELECT &apos;66&apos;, &apos;BOM&apos;
        /// UNION ALL SELECT &apos;17&apos;, &apos;SALES_ORDER&apos;
        /// UNION ALL SELECT &apos;13R&apos;, &apos;RESERVE_INVOICE&apos;
        /// UNION ALL SELECT &apos;14&apos;, &apos;AR_CN&apos;
        /// UNION ALL SELECT &apos;16&apos;, &apos;AR_RETURNS&apos;
        /// UNION ALL SELECT &apos;22&apos;, &apos;PURCH [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string axcOSYNC_GET_LIST_OBJECTS {
            get {
                return ResourceManager.GetString("axcOSYNC_GET_LIST_OBJECTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @FrCode NVARCHAR(50) = &apos;{0}&apos;
        ///DECLARE @ToCode NVARCHAR(50) = &apos;{1}&apos;
        ///SELECT &apos;N&apos; &quot;Export&quot;, &apos;N&apos; &quot;Success&quot;, T0.&quot;DocNum&quot;, CASE T0.CANCELED WHEN &apos;N&apos; THEN CASE T0.&quot;DocStatus&quot; WHEN &apos;C&apos; THEN &apos;Closed&apos; WHEN &apos;O&apos; THEN &apos;Open&apos; ELSE T0.&quot;DocStatus&quot; END ELSE &apos;Canceled&apos; END &quot;DocStatus&quot;
        ///	, T0.&quot;CardCode&quot;, T0.&quot;CardName&quot;
        ///	, T0.&quot;NumAtCard&quot; &quot;Cust Ref Num&quot;, T0.&quot;DocDate&quot; &quot;Posting Date&quot;, T0.&quot;DocDueDate&quot; &quot;Due Date&quot;, T0.&quot;TaxDate&quot; &quot;Doc Date&quot;
        ///	, T0.&quot;DocCur&quot; &quot;Currency&quot;, CASE ISNULL(T0.&quot;DocTotalFC&quot;,0) WHEN 0 THEN T0.&quot;DocTotal&quot; EL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string axcOSYNC_GET_LIST_OINV_RESERVE {
            get {
                return ResourceManager.GetString("axcOSYNC_GET_LIST_OINV_RESERVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --axcOSYNC_GET_LIST_OITB	
        ///DECLARE @FrCode NVARCHAR(254) = &apos;{0}&apos;
        ///DECLARE @ToCode NVARCHAR(254) = &apos;{1}&apos;
        ///SELECT &apos;N&apos; &quot;Export&quot;, &apos;N&apos; &quot;Success&quot;, T0.&quot;ItmsGrpNam&quot; &quot;Group Name&quot;, T0.&quot;ItmsGrpCod&quot; &quot;Group Code&quot;, T0.&quot;Locked&quot;, T0.&quot;ItmsGrpCod&quot; &quot;Key&quot;, T0.&quot;ItmsGrpNam&quot; &quot;Name&quot;, T0.&quot;Object&quot; &quot;ObjType&quot; 
        ///	, CAST(&apos;&apos; AS NVARCHAR(254)) &quot;Export Process Remark&quot;
        ///FROM OITB T0 
        ///WHERE T0.&quot;ItmsGrpNam&quot; BETWEEN @FrCode AND @ToCode
        ///	OR (
        ///		@FrCode = &apos;&apos; AND @ToCode = &apos;&apos;
        ///	).
        /// </summary>
        internal static string axcOSYNC_GET_LIST_OITB {
            get {
                return ResourceManager.GetString("axcOSYNC_GET_LIST_OITB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --axcOSYNC_GET_LIST_OITM
        ///DECLARE @FrCode NVARCHAR(50) = &apos;{0}&apos;
        ///DECLARE @ToCode NVARCHAR(50) = &apos;{1}&apos;
        ///DECLARE @InventoryItem NVARCHAR(1) = &apos;Y&apos;
        ///
        ///SELECT &apos;N&apos; &quot;Export&quot;, &apos;N&apos; &quot;Success&quot;, T0.&quot;ItemCode&quot;, T0.&quot;ItemName&quot;, T0.&quot;FrgnName&quot;, T1.&quot;ItmsGrpNam&quot; &quot;Group&quot;, T0.&quot;InvntryUom&quot; &quot;Inventory UOM&quot;, T0.&quot;BuyUnitMsr&quot; &quot;Purchase UOM&quot;
        ///	, T0.&quot;NumInBuy&quot; &quot;Items/Purch Unit&quot;, T0.&quot;SalUnitMsr&quot; &quot;Sales UOM&quot;, T0.&quot;NumInSale&quot; &quot;Items/Sale Unit&quot;, T0.&quot;CardCode&quot; &quot;Preferred Vendor&quot;
        ///	, CASE WHEN T0.&quot;validFor&quot; = &apos;Y&apos; THEN &apos;Y&apos; WHEN ISNULL(T0.&quot;val [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string axcOSYNC_GET_LIST_OITM {
            get {
                return ResourceManager.GetString("axcOSYNC_GET_LIST_OITM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --axcOSYNC_GET_LIST_OITT
        ///DECLARE @FrCode NVARCHAR(50) = &apos;{0}&apos;
        ///DECLARE @ToCode NVARCHAR(50) = &apos;{1}&apos;
        ///
        ///SELECT &apos;N&apos; &quot;Export&quot;, &apos;N&apos; &quot;Success&quot;,  T0.&quot;Code&quot;, T1.&quot;ItemName&quot; &quot;BOM Name&quot;, CASE T0.&quot;TreeType&quot; WHEN &apos;A&apos; THEN &apos;Assembly&apos; WHEN &apos;S&apos; THEN &apos;Sales&apos; WHEN &apos;P&apos; THEN &apos;Production&apos; WHEN &apos;T&apos; THEN &apos;Template&apos; END &quot;BOM Type&quot;,
        ///	T0.&quot;Qauntity&quot; &quot;Quantity&quot;, T0.&quot;Project&quot;, T0.&quot;Code&quot; &quot;Key&quot;, T1.&quot;ItemName&quot; &quot;Name&quot;, T0.&quot;Object&quot; &quot;ObjType&quot;
        ///	, CAST(&apos;&apos; AS NVARCHAR(254)) &quot;Export Process Remark&quot;
        ///FROM OITT T0 Inner Join OITM T1 on T0.&quot;Cod [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string axcOSYNC_GET_LIST_OITT {
            get {
                return ResourceManager.GetString("axcOSYNC_GET_LIST_OITT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --axcOSYNC_GET_LIST_OMRC
        ///DECLARE @FrCode NVARCHAR(50) = &apos;{0}&apos;
        ///DECLARE @ToCode NVARCHAR(50) = &apos;{1}&apos;
        ///
        ///SELECT &apos;N&apos; &quot;Export&quot;, &apos;N&apos; &quot;Success&quot;, T0.&quot;FirmName&quot;, T0.&quot;FirmCode&quot; &quot;Key&quot;, T0.&quot;FirmName&quot; &quot;Name&quot;, &apos;43&apos; &quot;ObjType&quot;
        ///	, CAST(&apos;&apos; AS NVARCHAR(254)) &quot;Export Process Remark&quot;
        ///FROM OMRC T0
        ///WHERE T0.&quot;FirmName&quot; BETWEEN @FrCode AND @ToCode
        ///	OR (@FrCode=&apos;&apos; AND @ToCode = &apos;&apos;)
        ///ORDER BY T0.&quot;FirmName&quot;.
        /// </summary>
        internal static string axcOSYNC_GET_LIST_OMRC {
            get {
                return ResourceManager.GetString("axcOSYNC_GET_LIST_OMRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @FrCode NVARCHAR(50) = &apos;{0}&apos;
        ///DECLARE @ToCode NVARCHAR(50) = &apos;{1}&apos;
        ///SELECT &apos;N&apos; &quot;Export&quot;, &apos;N&apos; &quot;Success&quot;, T0.&quot;DocNum&quot;, CASE T0.CANCELED WHEN &apos;N&apos; THEN CASE T0.&quot;DocStatus&quot; WHEN &apos;C&apos; THEN &apos;Closed&apos; WHEN &apos;O&apos; THEN &apos;Open&apos; ELSE T0.&quot;DocStatus&quot; END ELSE &apos;Canceled&apos; END &quot;DocStatus&quot;
        ///	, T0.&quot;CardCode&quot;, T0.&quot;CardName&quot;
        ///	, T0.&quot;NumAtCard&quot; &quot;Vendor Ref Num&quot;, T0.&quot;DocDate&quot; &quot;Posting Date&quot;, T0.&quot;DocDueDate&quot; &quot;Due Date&quot;, T0.&quot;TaxDate&quot; &quot;Doc Date&quot;
        ///	, T0.&quot;DocCur&quot; &quot;Currency&quot;, CASE ISNULL(T0.&quot;DocTotalFC&quot;,0) WHEN 0 THEN T0.&quot;DocTotal&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string axcOSYNC_GET_LIST_OPOR {
            get {
                return ResourceManager.GetString("axcOSYNC_GET_LIST_OPOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @FrCode NVARCHAR(50) = &apos;{0}&apos;
        ///DECLARE @ToCode NVARCHAR(50) = &apos;{1}&apos;
        ///SELECT &apos;N&apos; &quot;Export&quot;, &apos;N&apos; &quot;Success&quot;, T0.&quot;DocNum&quot;, CASE T0.CANCELED WHEN &apos;N&apos; THEN CASE T0.&quot;DocStatus&quot; WHEN &apos;C&apos; THEN &apos;Closed&apos; WHEN &apos;O&apos; THEN &apos;Open&apos; ELSE T0.&quot;DocStatus&quot; END ELSE &apos;Canceled&apos; END &quot;DocStatus&quot;
        ///	, T0.&quot;CardCode&quot;, T0.&quot;CardName&quot;
        ///	, T0.&quot;NumAtCard&quot; &quot;Cust Ref Num&quot;, T0.&quot;DocDate&quot; &quot;Posting Date&quot;, T0.&quot;DocDueDate&quot; &quot;Due Date&quot;, T0.&quot;TaxDate&quot; &quot;Doc Date&quot;
        ///	, T0.&quot;DocCur&quot; &quot;Currency&quot;, CASE ISNULL(T0.&quot;DocTotalFC&quot;,0) WHEN 0 THEN T0.&quot;DocTotal&quot; EL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string axcOSYNC_GET_LIST_ORDN {
            get {
                return ResourceManager.GetString("axcOSYNC_GET_LIST_ORDN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @FrCode NVARCHAR(50) = &apos;{0}&apos;
        ///DECLARE @ToCode NVARCHAR(50) = &apos;{1}&apos;
        ///SELECT &apos;N&apos; &quot;Export&quot;, &apos;N&apos; &quot;Success&quot;, T0.&quot;DocNum&quot;, CASE T0.CANCELED WHEN &apos;N&apos; THEN CASE T0.&quot;DocStatus&quot; WHEN &apos;C&apos; THEN &apos;Closed&apos; WHEN &apos;O&apos; THEN &apos;Open&apos; ELSE T0.&quot;DocStatus&quot; END ELSE &apos;Canceled&apos; END &quot;DocStatus&quot;
        ///	, T0.&quot;CardCode&quot;, T0.&quot;CardName&quot;
        ///	, T0.&quot;NumAtCard&quot; &quot;Cust Ref Num&quot;, T0.&quot;DocDate&quot; &quot;Posting Date&quot;, T0.&quot;DocDueDate&quot; &quot;Due Date&quot;, T0.&quot;TaxDate&quot; &quot;Doc Date&quot;
        ///	, T0.&quot;DocCur&quot; &quot;Currency&quot;, CASE ISNULL(T0.&quot;DocTotalFC&quot;,0) WHEN 0 THEN T0.&quot;DocTotal&quot; EL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string axcOSYNC_GET_LIST_ORDR {
            get {
                return ResourceManager.GetString("axcOSYNC_GET_LIST_ORDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @FrCode NVARCHAR(50) = &apos;{0}&apos;
        ///DECLARE @ToCode NVARCHAR(50) = &apos;{1}&apos;
        ///SELECT DISTINCT &apos;N&apos; &quot;Export&quot;, &apos;N&apos; &quot;Success&quot;, T0.&quot;DocNum&quot;, CASE T0.CANCELED WHEN &apos;N&apos; THEN CASE T0.&quot;DocStatus&quot; WHEN &apos;C&apos; THEN &apos;Closed&apos; WHEN &apos;O&apos; THEN &apos;Open&apos; ELSE T0.&quot;DocStatus&quot; END ELSE &apos;Canceled&apos; END &quot;DocStatus&quot;
        ///	, T0.&quot;CardCode&quot;, T0.&quot;CardName&quot;
        ///	, T0.&quot;NumAtCard&quot; &quot;Cust Ref Num&quot;, T0.&quot;DocDate&quot; &quot;Posting Date&quot;, T0.&quot;DocDueDate&quot; &quot;Due Date&quot;, T0.&quot;TaxDate&quot; &quot;Doc Date&quot;
        ///	, T0.&quot;DocCur&quot; &quot;Currency&quot;, CASE ISNULL(T0.&quot;DocTotalFC&quot;,0) WHEN 0 THEN T0.&quot;Doc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string axcOSYNC_GET_LIST_ORIN {
            get {
                return ResourceManager.GetString("axcOSYNC_GET_LIST_ORIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @FrCode NVARCHAR(50) = &apos;{0}&apos;
        ///DECLARE @ToCode NVARCHAR(50) = &apos;{1}&apos;
        ///SELECT &apos;N&apos; &quot;Export&quot;, &apos;N&apos; &quot;Success&quot;, T0.&quot;DocNum&quot;, CASE T0.CANCELED WHEN &apos;N&apos; THEN CASE T0.&quot;DocStatus&quot; WHEN &apos;C&apos; THEN &apos;Closed&apos; WHEN &apos;O&apos; THEN &apos;Open&apos; ELSE T0.&quot;DocStatus&quot; END ELSE &apos;Canceled&apos; END &quot;DocStatus&quot;
        ///	, T0.&quot;CardCode&quot;, T0.&quot;CardName&quot;
        ///	, T0.&quot;NumAtCard&quot; &quot;Vendor Ref Num&quot;, T0.&quot;DocDate&quot; &quot;Posting Date&quot;, T0.&quot;DocDueDate&quot; &quot;Due Date&quot;, T0.&quot;TaxDate&quot; &quot;Doc Date&quot;
        ///	, T0.&quot;DocCur&quot; &quot;Currency&quot;, CASE ISNULL(T0.&quot;DocTotalFC&quot;,0) WHEN 0 THEN T0.&quot;DocTotal&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string axcOSYNC_GET_LIST_ORPC {
            get {
                return ResourceManager.GetString("axcOSYNC_GET_LIST_ORPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @FrCode NVARCHAR(50) = &apos;{0}&apos;
        ///DECLARE @ToCode NVARCHAR(50) = &apos;{1}&apos;
        ///SELECT &apos;N&apos; &quot;Export&quot;, &apos;N&apos; &quot;Success&quot;, T0.&quot;DocNum&quot;, CASE T0.CANCELED WHEN &apos;N&apos; THEN CASE T0.&quot;DocStatus&quot; WHEN &apos;C&apos; THEN &apos;Closed&apos; WHEN &apos;O&apos; THEN &apos;Open&apos; ELSE T0.&quot;DocStatus&quot; END ELSE &apos;Canceled&apos; END &quot;DocStatus&quot;
        ///	, T0.&quot;CardCode&quot;, T0.&quot;CardName&quot;
        ///	, T0.&quot;NumAtCard&quot; &quot;Vendor Ref Num&quot;, T0.&quot;DocDate&quot; &quot;Posting Date&quot;, T0.&quot;DocDueDate&quot; &quot;Due Date&quot;, T0.&quot;TaxDate&quot; &quot;Doc Date&quot;
        ///	, T0.&quot;DocCur&quot; &quot;Currency&quot;, CASE ISNULL(T0.&quot;DocTotalFC&quot;,0) WHEN 0 THEN T0.&quot;DocTotal&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string axcOSYNC_GET_LIST_ORPD {
            get {
                return ResourceManager.GetString("axcOSYNC_GET_LIST_ORPD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --axcOSYNC_GET_LIST_OWHS		
        ///DECLARE @FrCode NVARCHAR(254) = &apos;{0}&apos;
        ///DECLARE @ToCode NVARCHAR(254) = &apos;{1}&apos;
        ///SELECT &apos;N&apos; &quot;Export&quot;, &apos;N&apos; &quot;Success&quot;, T0.&quot;WhsCode&quot;, T0.&quot;WhsName&quot; &quot;Whse Name&quot;, T0.&quot;Inactive&quot;, T0.&quot;BinActivat&quot; &quot;Bin Warehouse&quot;, T0.&quot;Street&quot;, T0.&quot;StreetNo&quot;, T0.&quot;Block&quot;, T0.&quot;WhsCode&quot; &quot;Key&quot;, T0.&quot;WhsName&quot; &quot;Name&quot;, T0.&quot;ObjType&quot; 
        ///	, CAST(&apos;&apos; AS NVARCHAR(254)) &quot;Export Process Remark&quot;
        ///FROM OWHS T0 
        ///WHERE T0.DropShip = &apos;N&apos; AND
        ///	(
        ///		T0.&quot;WhsCode&quot; BETWEEN @FrCode AND @ToCode
        ///		OR ( @FrCode = &apos;&apos; AND @ToCode = &apos;&apos; )
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string axcOSYNC_GET_LIST_OWHS {
            get {
                return ResourceManager.GetString("axcOSYNC_GET_LIST_OWHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --axcOSYNC_GET_LIST_OWOR
        ///DECLARE @FrCode NVARCHAR(50) = &apos;{0}&apos;
        ///DECLARE @ToCode NVARCHAR(50) = &apos;{1}&apos;
        ///SELECT &apos;N&apos; &quot;Export&quot;, &apos;N&apos; &quot;Success&quot;,  T0.&quot;DocNum&quot;
        ///	,CASE T0.&quot;Status&quot; WHEN &apos;P&apos; THEN &apos;Planned&apos; WHEN &apos;R&apos; THEN &apos;Released&apos; WHEN &apos;L&apos; THEN &apos;Closed&apos; WHEN &apos;C&apos; THEN &apos;Canceled&apos; END &quot;Status&quot;
        ///	, T0.&quot;ItemCode&quot;, T1.&quot;ItemName&quot; &quot;ProdName&quot;, T0.&quot;PlannedQty&quot;, T0.&quot;CmpltQty&quot; &quot;Completed Qty&quot;, T0.RjctQty &quot;Rejected Qty&quot;
        ///	, T0.&quot;Warehouse&quot;, T0.&quot;OriginNum&quot; &quot;SalesOrder&quot;,  T0.&quot;CardCode&quot; &quot;CustomerCode&quot;, T0.&quot;Project&quot;
        ///	, T0.&quot;PostDate&quot; &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string axcOSYNC_GET_LIST_OWOR {
            get {
                return ResourceManager.GetString("axcOSYNC_GET_LIST_OWOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --axcOSYNC_GET_LIST_VENDORS
        ///DECLARE @FrCode NVARCHAR(50) = &apos;{0}&apos;
        ///DECLARE @ToCode NVARCHAR(50) = &apos;{1}&apos;
        ///DECLARE @CardType NVARCHAR(1) = &apos;S&apos;
        ///
        ///SELECT &apos;N&apos; &quot;Export&quot;, &apos;N&apos; &quot;Success&quot;, T0.&quot;CardCode&quot;, T0.&quot;CardName&quot;, T0.&quot;CardFName&quot; &quot;Foreign Name&quot;, T1.&quot;GroupName&quot; &quot;Group&quot;, T0.&quot;CntctPrsn&quot; &quot;Contact Person&quot;, T0.&quot;Currency&quot;
        ///	, CASE WHEN T0.&quot;validFor&quot; = &apos;Y&apos; THEN &apos;Y&apos; WHEN ISNULL(T0.&quot;validFor&quot;,&apos;N&apos;) = &apos;N&apos; AND ISNULL(T0.&quot;frozenFor&quot;,&apos;N&apos;) = &apos;N&apos; THEN &apos;Y&apos; ELSE &apos;N&apos; END &quot;Active&quot;
        ///	, T0.&quot;CardCode&quot; &quot;Key&quot;, T0.&quot;CardName&quot; &quot;Name&quot;, T0.&quot;O [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string axcOSYNC_GET_LIST_VENDORS {
            get {
                return ResourceManager.GetString("axcOSYNC_GET_LIST_VENDORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.USERID, T0.U_NAME
        ///FROM OUSR T0 LEFT JOIN  [@AXC_FTIS1] T1 ON T0.USERID = T1.U_AXC_USRID
        ///WHERE T1.U_AXC_USRID IS NULL.
        /// </summary>
        internal static string FTIS1_GET_UNMAPPED_USER {
            get {
                return ResourceManager.GetString("FTIS1_GET_UNMAPPED_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T1.* FROM OCRD T0 JOIN  CRD1 T1 ON T0.CardCode = T1.CardCode  AND T1.AdresType = &apos;B&apos; AND T1.Address = T0.BillToDef WHERE T0.CardCode = &apos;{0}&apos;.
        /// </summary>
        internal static string GET_RECORD_CRD1_DEFAULT_BILL_TO {
            get {
                return ResourceManager.GetString("GET_RECORD_CRD1_DEFAULT_BILL_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM CRD1 WHERE AdresType = &apos;S&apos; AND &quot;CardCode&quot; = &apos;{0}&apos;.
        /// </summary>
        internal static string GET_RECORD_CRD1_SHIPTO {
            get {
                return ResourceManager.GetString("GET_RECORD_CRD1_SHIPTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT A.&quot;DocEntry&quot;,A.&quot;LineNum&quot;,A.&quot;ItemCode&quot;,A.&quot;ItemDesc&quot;  &quot;ItemName&quot;
        ///,A.&quot;InWhsQty&quot;,A.&quot;Counted&quot; &quot;IsCounted&quot;,A.&quot;CountQty&quot;,A.&quot;WhsCode&quot;
        ///,ISNULL(B.&quot;BinCode&quot;,&apos;&apos;) &quot;BinCode&quot;,ISNULL(C.&quot;InvntryUom&quot;,&apos;&apos;) &quot;InvntryUom&quot;
        ///,ISNULL(E.&quot;DistNumber&quot;,ISNULL(F.&quot;DistNumber&quot;,&apos;&apos;)) &quot;SnBCode&quot;
        ///FROM INC1 A
        ///LEFT JOIN OBIN B ON A.&quot;BinEntry&quot; = B.&quot;AbsEntry&quot;
        ///LEFT JOIN OITM C ON A.&quot;ItemCode&quot; = C.&quot;ItemCode&quot;
        ///LEFT JOIN INC3 D ON A.&quot;DocEntry&quot; = D.&quot;DocEntry&quot; and A.&quot;LineNum&quot; = D.&quot;LineNum&quot;
        ///LEFT join OBTN E on D.&quot;ObjId&quot; = E.&quot;ObjType&quot; and D.&quot;O [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GET_RECORD_INC1 {
            get {
                return ResourceManager.GetString("GET_RECORD_INC1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DocEntry, LineNum, ItemCode, unitMsr, OpenQty, OpenInvQty, Dscription, FreeTxt, WhsCode FROM INV1 WHERE DocEntry = {0}.
        /// </summary>
        internal static string GET_RECORD_INV1 {
            get {
                return ResourceManager.GetString("GET_RECORD_INV1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT A.*, B.&quot;ItemName&quot;,B.&quot;InvntryUom&quot; &quot;iUOM&quot; FROM ITT1 A
        ///inner join OITM B on A.&quot;Code&quot; = B.&quot;ItemCode&quot;
        ///WHERE A.&quot;Father&quot; = &apos;{0}&apos; AND A.&quot;Type&quot; = 4.
        /// </summary>
        internal static string GET_RECORD_ITT1_ITEMS {
            get {
                return ResourceManager.GetString("GET_RECORD_ITT1_ITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.*, T1.UomCode, T1.UomName FROM  OBCD T0 JOIN OUOM T1 ON T0.UomEntry = T1.UomEntry WHERE T0.BcdEntry = {0}.
        /// </summary>
        internal static string GET_RECORD_OBCD {
            get {
                return ResourceManager.GetString("GET_RECORD_OBCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM OBIN WHERE &quot;AbsEntry&quot;= &apos;{0}&apos;.
        /// </summary>
        internal static string GET_RECORD_OBIN {
            get {
                return ResourceManager.GetString("GET_RECORD_OBIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM OCRD WHERE &quot;CardCode&quot; = &apos;{0}&apos;.
        /// </summary>
        internal static string GET_RECORD_OCRD {
            get {
                return ResourceManager.GetString("GET_RECORD_OCRD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TOP 1 ISNULL(T2.CntctCode, T1.CntctCode) CntctCode, ISNULL(T2.Name, T1.Name)  &quot;Name&quot;
        ///FROM OCRD T0 JOIN OCPR T1 ON T0.CardCode = T1.CardCode
        ///	LEFT JOIN OCPR T2 ON T0.CntctPrsn = T2.Name
        /// WHERE T0.CardCode = &apos;{0}&apos;.
        /// </summary>
        internal static string GET_RECORD_OCRD_DEFAULT_CONTACT {
            get {
                return ResourceManager.GetString("GET_RECORD_OCRD_DEFAULT_CONTACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T1.* FROM OCRD T0 JOIN OSLP T1 ON T0.SlpCode = T1.SlpCode WHERE T0.CardCode = &apos;{0}&apos;.
        /// </summary>
        internal static string GET_RECORD_OCRD_DEFAULT_SALES_EMPLOYEE {
            get {
                return ResourceManager.GetString("GET_RECORD_OCRD_DEFAULT_SALES_EMPLOYEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT &quot;DocEntry&quot;, &quot;DocNum&quot;, &quot;CountDate&quot;,&quot;Status&quot;,&quot;Ref2&quot;,&quot;Remarks&quot;
        ///FROM OINC WHERE &quot;DocEntry&quot; = {0}.
        /// </summary>
        internal static string GET_RECORD_OINC {
            get {
                return ResourceManager.GetString("GET_RECORD_OINC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.DocEntry, T0.DocNum, T0.DocDate, T0.DocDueDate, T0.CardCode, T0.CardName, T0.NumAtCard, T0.ShipToCode, T0.Comments, T0.SlpCode, T1.SlpName
        ///	, CASE WHEN ISNULL(T0.U_AXC_DDLVR,&apos;-&apos;) IN (&apos;&apos;,&apos;-&apos;) THEN &apos;N&apos; ELSE   T0.U_AXC_DDLVR END DirectDelivery, T0.&quot;CANCELED&quot;
        ///FROM OINV T0 LEFT JOIN OSLP T1 ON T0.SlpCode = T1.SlpCode
        ///WHERE DocEntry = 0{0}.
        /// </summary>
        internal static string GET_RECORD_OINV {
            get {
                return ResourceManager.GetString("GET_RECORD_OINV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM OITB WHERE &quot;ItmsGrpCod&quot; = &apos;{0}&apos;.
        /// </summary>
        internal static string GET_RECORD_OITB {
            get {
                return ResourceManager.GetString("GET_RECORD_OITB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.ItemCode, T0.ItemName, T0.FrgnName, T0.InvntryUom, T0.SalUnitMsr, T0.BuyUnitMsr, T0.CardCode, T0.ItmsGrpCod, T1.ItmsGrpNam
        ///	, T0.ManSerNum, T0.ManBtchNum, T0.DfltWH, T3.BinCode
        ///	, T0.BLength1, T0.BLen1Unit
        ///	, T0.BWidth1, T0.BWdth1Unit
        ///	, T0.BHeight1, T0.BHght1Unit
        ///	, T0.BVolume, T0.BVolUnit
        ///	, T0.validFor, T0.frozenFor
        ///	, T4.BitmapPath, T0.PicturName
        ///	, T0.CreateDate, T0.CreateTS
        ///	, T0.UpdateDate, T0.UpdateTS
        ///	, T0.U_PRANK
        ///	, T0.PrchseItem, T0.SellItem, T0.InvntItem 
        ///FROM OITM T0 JOIN  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GET_RECORD_OITM {
            get {
                return ResourceManager.GetString("GET_RECORD_OITM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select *,B.&quot;ItemName&quot; &quot;Name&quot; from OITT A
        ///inner join OITM B on A.&quot;Code&quot; = B.&quot;ItemCode&quot;
        ///Where A.&quot;Code&quot; = &apos;{0}&apos;.
        /// </summary>
        internal static string GET_RECORD_OITT {
            get {
                return ResourceManager.GetString("GET_RECORD_OITT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM OMRC WHERE FirmCode= &apos;{0}&apos;.
        /// </summary>
        internal static string GET_RECORD_OMRC {
            get {
                return ResourceManager.GetString("GET_RECORD_OMRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.DocEntry, T0.DocNum, T0.DocDate, T0.DocDueDate, T0.CardCode, T0.CardName, T0.NumAtCard, T0.ShipToCode, T0.Comments, T0.SlpCode, T1.SlpName
        ///	, DocCur, DocRate, T0.&quot;CANCELED&quot;, T0.&quot;DocStatus&quot;
        ///FROM OPOR T0 LEFT JOIN OSLP T1 ON T0.SlpCode = T1.SlpCode
        ///WHERE DocEntry = {0}.
        /// </summary>
        internal static string GET_RECORD_OPOR {
            get {
                return ResourceManager.GetString("GET_RECORD_OPOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM ORDN WHERE &quot;DocEntry&quot; = &apos;{0}&apos;.
        /// </summary>
        internal static string GET_RECORD_ORDN {
            get {
                return ResourceManager.GetString("GET_RECORD_ORDN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.DocEntry, T0.DocNum, T0.DocDate, T0.DocDueDate, T0.CardCode, T0.CardName, T0.NumAtCard, T0.ShipToCode, T0.Comments, T0.SlpCode, T1.SlpName,T0.DocStatus,T0.&quot;CANCELED&quot; , T0.&quot;DocStatus&quot;
        ///	, CASE WHEN ISNULL(T0.U_AXC_DDLVR,&apos;-&apos;) IN (&apos;&apos;,&apos;-&apos;) THEN &apos;N&apos; ELSE   T0.U_AXC_DDLVR END DirectDelivery
        ///FROM ORDR T0 LEFT JOIN OSLP T1 ON T0.SlpCode = T1.SlpCode
        ///WHERE DocEntry = 0{0}.
        /// </summary>
        internal static string GET_RECORD_ORDR {
            get {
                return ResourceManager.GetString("GET_RECORD_ORDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TOP 1 T0.ObjType, T0.DocEntry, T0.DocNum, T0.NumAtCard, T0.DocDate, T0.DocDueDate,
        ///	T0.CardCode, T2.DocEntry BaseEntry, T2. DocNum BaseRef,  T2.U_AXC_EXTID 
        ///FROM ORIN T0  JOIN RIN1 T1 ON T0.DocEntry = T1.DocEntry 
        ///	LEFT JOIN (ORDN T2 JOIN RDN1 T3 ON T2.DocEntry = T3.DocEntry) ON T1.BaseType = T2.ObjType AND T1.BaseEntry = T2.DocEntry AND T1.BaseLine = T3.LineNum AND ISNULL(T2.U_AXC_EXTID,&apos;&apos;) &lt;&gt; &apos;&apos; 
        ///WHERE T0.DocEntry = {0}
        ///ORDER BY T1.BaseEntry.
        /// </summary>
        internal static string GET_RECORD_ORIN {
            get {
                return ResourceManager.GetString("GET_RECORD_ORIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM ORPC WHERE &quot;DocEntry&quot; = &apos;{0}&apos;.
        /// </summary>
        internal static string GET_RECORD_ORPC {
            get {
                return ResourceManager.GetString("GET_RECORD_ORPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TOP 1 T0.ObjType, T0.DocEntry, T0.DocNum, T0.NumAtCard, T0.DocDate, T0.DocDueDate,
        ///	T0.CardCode, T1.BaseEntry, T1.BaseRef 
        ///FROM ORPD T0  JOIN RPD1 T1 ON T0.DocEntry = T1.DocEntry 
        ///WHERE T0.DocEntry = {0}
        ///ORDER BY T1.BaseEntry.
        /// </summary>
        internal static string GET_RECORD_ORPD {
            get {
                return ResourceManager.GetString("GET_RECORD_ORPD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM OWHS WHERE &quot;WhsCode&quot;= &apos;{0}&apos;.
        /// </summary>
        internal static string GET_RECORD_OWHS {
            get {
                return ResourceManager.GetString("GET_RECORD_OWHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM OWOR WHERE &quot;DocEntry&quot;= &apos;{0}&apos;.
        /// </summary>
        internal static string GET_RECORD_OWOR {
            get {
                return ResourceManager.GetString("GET_RECORD_OWOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DocEntry, LineNum, ItemCode, unitMsr, OpenQty, OpenInvQty, Dscription, FreeTxt, WhsCode FROM POR1 WHERE DocEntry = {0}.
        /// </summary>
        internal static string GET_RECORD_POR1 {
            get {
                return ResourceManager.GetString("GET_RECORD_POR1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DocEntry, LineNum, ItemCode, unitMsr, OpenQty, OpenInvQty, Dscription, FreeTxt, WhsCode FROM RDR1 WHERE DocEntry = {0}.
        /// </summary>
        internal static string GET_RECORD_RDR1 {
            get {
                return ResourceManager.GetString("GET_RECORD_RDR1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DocEntry, LineNum, ItemCode, unitMsr, OpenQty, OpenInvQty, Dscription, FreeTxt, WhsCode FROM RPD1 WHERE DocEntry = {0}.
        /// </summary>
        internal static string GET_RECORD_RPD1 {
            get {
                return ResourceManager.GetString("GET_RECORD_RPD1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.DocEntry, T0.LineNum, T0.ItemCode, T0.BaseQty, T1.ItemName
        ///, T0.PlannedQty, T0.wareHouse, T0.IssueType, T0.ItemType, T1.InvntryUom 
        ///FROM WOR1 T0 JOIN OITM T1 ON T0.ItemCode= T1.ItemCode 
        ///WHERE T0.ItemType = 4 AND T0.DocEntry = {0}.
        /// </summary>
        internal static string GET_RECORD_WOR1 {
            get {
                return ResourceManager.GetString("GET_RECORD_WOR1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT &apos;%&apos;, &apos;Both&apos;
        ///UNION ALL SELECT &apos;I&apos;, &apos;Inbound&apos;
        ///UNION ALL SELECT &apos;O&apos;, &apos;Outbound&apos;.
        /// </summary>
        internal static string OFTLOG_GET_COMBO_BOX_DIRECTION {
            get {
                return ResourceManager.GetString("OFTLOG_GET_COMBO_BOX_DIRECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT &apos;%&apos; Code, &apos;All&apos; Name
        ///UNION ALL SELECT &apos;2V&apos; &quot;Code&quot;, &apos;VENDOR&apos; &quot;Name&quot; 
        ///UNION ALL SELECT &apos;2C&apos;, &apos;CUSTOMER&apos;
        ///UNION ALL SELECT &apos;4&apos;, &apos;ITEM&apos;
        ///UNION ALL SELECT &apos;52&apos;, &apos;ITEM_CATEGORY&apos;
        ///UNION ALL SELECT &apos;43&apos;, &apos;BRAND&apos;
        ///UNION ALL SELECT &apos;1470000062&apos;, &apos;BAR_CODE&apos;
        ///UNION ALL SELECT &apos;64&apos;, &apos;WAREHOUSE&apos;
        ///UNION ALL SELECT &apos;10000206&apos;, &apos;BIN&apos;
        ///UNION ALL SELECT &apos;66&apos;, &apos;BOM&apos;
        ///UNION ALL SELECT &apos;17&apos;, &apos;SALES_ORDER&apos;
        ///UNION ALL SELECT &apos;13R&apos;, &apos;RESERVE_INVOICE&apos;
        ///UNION ALL SELECT &apos;14&apos;, &apos;AR_CN&apos;
        ///UNION ALL SELECT &apos;16&apos;, &apos;AR_RETURN&apos;
        ///UNIO [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OFTLOG_GET_COMBO_BOX_OBJECTS {
            get {
                return ResourceManager.GetString("OFTLOG_GET_COMBO_BOX_OBJECTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT USERID, USER_CODE FROM (
        ///SELECT 0 idx, &apos;%&apos; USERID, &apos;All&apos; USER_CODE UNION ALL
        ///SELECT ROW_NUMBER() OVER(ORDER BY USER_CODE ASC),  CAST(USERID AS NVARCHAR(13)) USERID, USER_CODE FROM OUSR
        ///) X
        ///ORDER BY idx.
        /// </summary>
        internal static string OFTLOG_GET_COMBO_BOX_USERS {
            get {
                return ResourceManager.GetString("OFTLOG_GET_COMBO_BOX_USERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @Object NVARCHAR(50) = &apos;{0}&apos;
        ///DECLARE @Success NVARCHAR(1) = &apos;{1}&apos;
        ///DECLARE @FrDate NVARCHAR(8) = &apos;{2}&apos;
        ///DECLARE @ToDate NVARCHAR(8) = &apos;{3}&apos;
        ///DECLARE @User NVARCHAR(20) = &apos;{4}&apos;
        ///DECLARE @Direction NVARCHAR(1) = &apos;{5}&apos;
        ///
        ///SELECT T0.&quot;Code&quot; ID
        ///	, U_AXC_TSTMP &quot;TimeStamp&quot;
        ///	, T1.USER_CODE &quot;User&quot;
        ///	, T0.U_AXC_DRCTN &quot;Direction&quot;
        ///	, T0.U_AXC_OPRTN &quot;Method&quot;
        ///	, T0.U_AXC_OBJTP &quot;WMSObjectType&quot;
        ///	, T0.U_AXC_OBJCD &quot;Code&quot;
        ///	, T0.U_AXC_OBJNM &quot;Name&quot;
        ///	, T0.U_AXC_EXTID &quot;Ext.ID&quot;
        ///	, T0.U_AXC_SCCES &quot;Success&quot;
        ///	, T0.U_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OFTLOG_GET_LOG {
            get {
                return ResourceManager.GetString("OFTLOG_GET_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @ObjType int = {0}
        ///DECLARE @DocEntry int = {1}
        ///
        ///
        ///SELECT ROW_NUMBER() OVER (ORDER BY X.LineNum, X.SnbAbsEntry, X.BinAbs) LineKey, X.*, X1.FreeTxt, X1.U_AXC_EXTID FROM (
        ///	SELECT MIN(T0.[TransType]) ObjType, MIN(T0.[CreatedBy]) DocEntry, MIN(T0.[BASE_REF]) DocNum, MIN(T0.[DocLineNum]) LineNum, 
        ///		MIN(T0.[ItemCode]) ItemCode, MIN(T0.[Dscription]) ItemName, MIN(T0.[InvPLInQty]) [InvPLInQty], MIN(T0.[InvPLOutQty]) [InvPLOutQty], 
        ///		MIN(T0.[Warehouse]) Warehouse, MIN(T1.[InvntryUom]) InvntryUom
        ///		, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OINM_GET_LINE_SNB_BIN_INFO {
            get {
                return ResourceManager.GetString("OINM_GET_LINE_SNB_BIN_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T1.*, T2.&quot;UomCode&quot;, T2.&quot;UomName&quot; 
        ///FROM OITM T0 INNER JOIN OBCD T1 ON T0.&quot;ItemCode&quot; = T1.&quot;ItemCode&quot;  
        ///	LEFT JOIN OUOM T2 ON T1.&quot;UomEntry&quot; = T2.&quot;UomEntry&quot;  
        ///WHERE T0.&quot;ItemCode&quot; = &apos;{0}&apos;.
        /// </summary>
        internal static string OITM_GET_BARCODES {
            get {
                return ResourceManager.GetString("OITM_GET_BARCODES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT(&apos;&apos;) FROM OIVL WHERE TransType = {0} AND CreatedBy = {1}.
        /// </summary>
        internal static string OIVL_DOCUMENT_HAS_INVENTORY_MOVEMENT {
            get {
                return ResourceManager.GetString("OIVL_DOCUMENT_HAS_INVENTORY_MOVEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT &apos;0&apos; &quot;FirmCode&quot;, &apos;&apos; &quot;FirmName&quot;
        ///UNION ALL SELECT CAST(&quot;FirmCode&quot; AS NVARCHAR(12)), &quot;FirmName&quot; FROM OMRC 
        ///ORDER BY &quot;FirmName&quot;.
        /// </summary>
        internal static string OMRC_GET_FIRM_NAMES {
            get {
                return ResourceManager.GetString("OMRC_GET_FIRM_NAMES", resourceCulture);
            }
        }
    }
}
